const mockProperties = [
    {
        id: 1,
        title: "Magnifique Appartement Haussmannien",
        price: 1550000,
        type: "Apartment",
        area: 120,
        rooms: 4,
        bedrooms: 3,
        energyClass: "D",
        features: ["Balcony", "Elevator"],
        image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800",
        address: "75008 Paris, France",
        lat: 48.8727,
        lng: 2.3126,
        description: "Superb Haussmannian apartment near Champs-Élysées with original moldings, Point de Hongrie parquet floors, and marble fireplaces.",
        link: "#"
    },
    {
        id: 2,
        title: "Charming Le Marais Studio",
        price: 380000,
        type: "Studio",
        area: 28,
        rooms: 1,
        bedrooms: 0,
        energyClass: "E",
        features: [],
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
        address: "75003 Paris, France",
        lat: 48.8598,
        lng: 2.3614,
        description: "Perfect pied-à-terre in the heart of Le Marais. Exposed beams and modern renovations make this a cozy gem.",
        link: "#"
    },
    {
        id: 3,
        title: "Modern Duplex near Canal Saint-Martin",
        price: 1100000,
        type: "Apartment",
        area: 95,
        rooms: 4,
        bedrooms: 2,
        energyClass: "B",
        features: ["Terrace", "Elevator", "Parking"],
        image: "https://images.unsplash.com/photo-1502672260266-1c1529801574?auto=format&fit=crop&q=80&w=800",
        address: "75010 Paris, France",
        lat: 48.8738,
        lng: 2.3650,
        description: "Contemporary duplex with a large sunny terrace overlooking the canal. Includes secure underground parking.",
        link: "#"
    },
    {
        id: 4,
        title: "Rare Townhouse in Montmartre",
        price: 2400000,
        type: "House",
        area: 180,
        rooms: 6,
        bedrooms: 4,
        energyClass: "C",
        features: ["Terrace", "Balcony"],
        image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800",
        address: "75018 Paris, France",
        lat: 48.8872,
        lng: 2.3386,
        description: "Exceptional private house tucked away in Montmartre with a private garden, terrace, and stunning city views.",
        link: "#"
    },
    {
        id: 5,
        title: "Elegant Family Apartment Passy",
        price: 1850000,
        type: "Apartment",
        area: 145,
        rooms: 5,
        bedrooms: 3,
        energyClass: "C",
        features: ["Elevator", "Parking"],
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
        address: "75016 Paris, France",
        lat: 48.8580,
        lng: 2.2818,
        description: "Spacious and bright family apartment in the prestigious 16th arrondissement. Secure building with concierge.",
        link: "#"
    },
    {
        id: 6,
        title: "Cozy Studio near Sorbonne",
        price: 410000,
        type: "Studio",
        area: 32,
        rooms: 1,
        bedrooms: 0,
        energyClass: "F",
        features: ["Elevator"],
        image: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80&w=800",
        address: "75005 Paris, France",
        lat: 48.8483,
        lng: 2.3435,
        description: "Student-friendly studio in the Latin Quarter. Very close to universities and public transit.",
        link: "#"
    },
    {
        id: 7,
        title: "Penthouse with Eiffel Tower View",
        price: 3200000,
        type: "Apartment",
        area: 210,
        rooms: 6,
        bedrooms: 4,
        energyClass: "B",
        features: ["Terrace", "Balcony", "Elevator", "Parking"],
        image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=800",
        address: "75007 Paris, France",
        lat: 48.8581,
        lng: 2.3015,
        description: "Breathtaking penthouse apartment offering a wrap-around terrace and unobstructed views of the Eiffel Tower.",
        link: "#"
    },
    {
        id: 8,
        title: "Renovated Loft in Belleville",
        price: 850000,
        type: "Apartment",
        area: 88,
        rooms: 3,
        bedrooms: 2,
        energyClass: "C",
        features: ["Parking"],
        image: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800",
        address: "75020 Paris, France",
        lat: 48.8719,
        lng: 2.3871,
        description: "Industrial style loft in a former workshop. Very bright with a large skylight and open-plan kitchen.",
        link: "#"
    },
    {
        id: 9,
        title: "Quiet House in La Butte aux Cailles",
        price: 1350000,
        type: "House",
        area: 110,
        rooms: 4,
        bedrooms: 3,
        energyClass: "D",
        features: ["Terrace"],
        image: "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&q=80&w=800",
        address: "75013 Paris, France",
        lat: 48.8278,
        lng: 2.3508,
        description: "Extremely rare village-style house in Paris. Quiet cobblestone street layout with a private sunny courtyard.",
        link: "#"
    },
    {
        id: 10,
        title: "Luxury Apartment Ile Saint-Louis",
        price: 2800000,
        type: "Apartment",
        area: 135,
        rooms: 5,
        bedrooms: 2,
        energyClass: "D",
        features: ["Balcony", "Elevator"],
        image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&q=80&w=800",
        address: "75004 Paris, France",
        lat: 48.8521,
        lng: 2.3563,
        description: "Historic apartment on the exclusive Ile Saint-Louis holding spectacular views over the Seine.",
        link: "#"
    },
    {
        id: 11,
        title: "Bright Studio near Bastille",
        price: 320000,
        type: "Studio",
        area: 24,
        rooms: 1,
        bedrooms: 0,
        energyClass: "G",
        features: [],
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800",
        address: "75011 Paris, France",
        lat: 48.8533,
        lng: 2.3693,
        description: "Top floor studio apartment, requires some energy class updating but offers great potential and brightness.",
        link: "#"
    },
    {
        id: 12,
        title: "New Build Apartment Batignolles",
        price: 980000,
        type: "Apartment",
        area: 75,
        rooms: 3,
        bedrooms: 2,
        energyClass: "A",
        features: ["Balcony", "Elevator", "Parking"],
        image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
        address: "75017 Paris, France",
        lat: 48.8835,
        lng: 2.3168,
        description: "Eco-friendly modern apartment in the new eco-district. Highly energy efficient with a long balcony.",
        link: "#"
    },
    {
        id: 13,
        title: "Art Deco Apartment Vaugirard",
        price: 745000,
        type: "Apartment",
        area: 68,
        rooms: 3,
        bedrooms: 2,
        energyClass: "E",
        features: ["Elevator"],
        image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800",
        address: "75015 Paris, France",
        lat: 48.8415,
        lng: 2.3005,
        description: "Charming 1930s apartment with beautiful bow windows and original character in a quiet residential area.",
        link: "#"
    },
    {
        id: 14,
        title: "Architect House Montparnasse",
        price: 1950000,
        type: "House",
        area: 165,
        rooms: 6,
        bedrooms: 4,
        energyClass: "C",
        features: ["Terrace", "Parking"],
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=800",
        address: "75014 Paris, France",
        lat: 48.8351,
        lng: 2.3268,
        description: "Unique contemporary house hidden behind a courtyard. Features a glass roof living area and interior patio.",
        link: "#"
    },
    {
        id: 15,
        title: "Classic Apartment Saint-Germain",
        price: 2150000,
        type: "Apartment",
        area: 110,
        rooms: 4,
        bedrooms: 2,
        energyClass: "D",
        features: ["Elevator"],
        image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=800",
        address: "75006 Paris, France",
        lat: 48.8530,
        lng: 2.3325,
        description: "Quintessential Parisian elegance in Saint-Germain-des-Prés. High ceilings, long balcony, and prestegious address.",
        link: "#"
    },
    {
        id: 16,
        title: "Large Family Home in Auteuil",
        price: 3500000,
        type: "House",
        area: 250,
        rooms: 8,
        bedrooms: 5,
        energyClass: "C",
        features: ["Terrace", "Balcony", "Parking"],
        image: "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&q=80&w=800",
        address: "75016 Paris, France",
        lat: 48.8465,
        lng: 2.2625,
        description: "A gorgeous family home in the exclusive Auteuil neighborhood featuring a private driveway, garden, and large terrace.",
        link: "#"
    },
    {
        id: 17,
        title: "Modern Studio near La Villette",
        price: 295000,
        type: "Studio",
        area: 22,
        rooms: 1,
        bedrooms: 0,
        energyClass: "D",
        features: ["Elevator"],
        image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&q=80&w=800",
        address: "75019 Paris, France",
        lat: 48.8921,
        lng: 2.3850,
        description: "Excellent investment property near the beautiful Parc de la Villette. Recently renovated and highly optimized space.",
        link: "#"
    },
    {
        id: 18,
        title: "Artist Apartment in Pigalle",
        price: 680000,
        type: "Apartment",
        area: 60,
        rooms: 2,
        bedrooms: 1,
        energyClass: "E",
        features: ["Balcony"],
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800",
        address: "75009 Paris, France",
        lat: 48.8821,
        lng: 2.3364,
        description: "Bohemian chic apartment located in lively South Pigalle. Featues high ceilings and a sunny wrought-iron balcony.",
        link: "#"
    },
    {
        id: 19,
        title: "Luxurious Hotel Particulier",
        price: 5200000,
        type: "House",
        area: 400,
        rooms: 10,
        bedrooms: 6,
        energyClass: "B",
        features: ["Terrace", "Elevator", "Parking"],
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
        address: "75008 Paris, France",
        lat: 48.8742,
        lng: 2.3087,
        description: "An incredibly rare Hôtel Particulier off the Champs-Élysées. Completely restored with a private internal elevator and secure parking.",
        link: "#"
    },
    {
        id: 20,
        title: "Cozy Flat in Saint-Ambroise",
        price: 510000,
        type: "Apartment",
        area: 45,
        rooms: 2,
        bedrooms: 1,
        energyClass: "C",
        features: [],
        image: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&q=80&w=800",
        address: "75011 Paris, France",
        lat: 48.8614,
        lng: 2.3787,
        description: "A warm and inviting one-bedroom apartment near Richard Lenoir. Features exposed brick and a beautiful custom-built kitchen.",
        link: "#"
    }
];
