const mockProperties = [
    {
        id: 1,
        title: "Luxury Condo in Belltown",
        price: 1550000,
        type: "Apartment",
        area: 1250,
        rooms: 4,
        bedrooms: 2,
        features: ["Balcony", "Elevator", "Central AC", "Parking"],
        image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800",
        address: "98121 Seattle, WA",
        lat: 47.6145,
        lng: -122.3486,
        description: "Stunning high-rise condo with Elliott Bay views. Floor-to-ceiling windows, chef's kitchen, and 24/7 concierge.",
        link: "#"
    },
    {
        id: 2,
        title: "Cozy Capitol Hill Studio",
        price: 380000,
        type: "Studio",
        area: 450,
        rooms: 1,
        bedrooms: 0,
        features: ["Elevator"],
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800",
        address: "98122 Seattle, WA",
        lat: 47.6152,
        lng: -122.3182,
        description: "Perfect pied-à-terre in the heart of Capitol Hill. Steps away from light rail, cafes, and nightlife.",
        link: "#"
    },
    {
        id: 3,
        title: "Modern Townhome in Ballard",
        price: 1100000,
        type: "House",
        area: 1600,
        rooms: 5,
        bedrooms: 3,
        features: ["Terrace", "Central AC", "Parking"],
        image: "https://images.unsplash.com/photo-1502672260266-1c1529801574?auto=format&fit=crop&q=80&w=800",
        address: "98107 Seattle, WA",
        lat: 47.6686,
        lng: -122.3847,
        description: "Contemporary Built Green townhome featuring a rooftop deck with mountain views and dedicated off-street parking.",
        link: "#"
    },
    {
        id: 4,
        title: "Classic Craftsman in Queen Anne",
        price: 2400000,
        type: "House",
        area: 3200,
        rooms: 8,
        bedrooms: 4,
        features: ["Terrace", "Parking", "Central AC"],
        image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800",
        address: "98109 Seattle, WA",
        lat: 47.6335,
        lng: -122.3571,
        description: "Meticulously restored historic Craftsman on a coveted Queen Anne street. Massive wrap-around porch and mature garden.",
        link: "#"
    },
    {
        id: 5,
        title: "Spacious Condo on First Hill",
        price: 950000,
        type: "Apartment",
        area: 1400,
        rooms: 4,
        bedrooms: 2,
        features: ["Elevator", "Parking"],
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
        address: "98104 Seattle, WA",
        lat: 47.6083,
        lng: -122.3243,
        description: "Bright corner unit walking distance to hospitals and downtown. Great value with secure garage parking included.",
        link: "#"
    },
    {
        id: 6,
        title: "U-District Student Studio",
        price: 310000,
        type: "Studio",
        area: 380,
        rooms: 1,
        bedrooms: 0,
        features: ["Elevator"],
        image: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80&w=800",
        address: "98105 Seattle, WA",
        lat: 47.6599,
        lng: -122.3134,
        description: "Excellent investment blocks from the University of Washington campus. Low HOA dues and high rentability.",
        link: "#"
    },
    {
        id: 7,
        title: "Penthouse in South Lake Union",
        price: 3200000,
        type: "Apartment",
        area: 2800,
        rooms: 6,
        bedrooms: 3,
        features: ["Terrace", "Balcony", "Elevator", "Parking", "Central AC"],
        image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=800",
        address: "98109 Seattle, WA",
        lat: 47.6253,
        lng: -122.3364,
        description: "Breathtaking penthouse above SLU. Wrap-around terrace overlooking Lake Union and the Space Needle.",
        link: "#"
    },
    {
        id: 8,
        title: "Industrial Loft in Pioneer Square",
        price: 850000,
        type: "Apartment",
        area: 1100,
        rooms: 2,
        bedrooms: 1,
        features: ["Elevator"],
        image: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800",
        address: "98104 Seattle, WA",
        lat: 47.6015,
        lng: -122.3331,
        description: "Historic loft with exposed brick walls, timber beams, and soaring 14-foot ceilings. A true creative space.",
        link: "#"
    },
    {
        id: 9,
        title: "Quiet Bungalow in Green Lake",
        price: 1150000,
        type: "House",
        area: 1850,
        rooms: 6,
        bedrooms: 3,
        features: ["Terrace", "Parking"],
        image: "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&q=80&w=800",
        address: "98115 Seattle, WA",
        lat: 47.6816,
        lng: -122.3275,
        description: "Charming updated bungalow just two blocks from Green Lake park. Features a sunny backyard and detached garage.",
        link: "#"
    },
    {
        id: 10,
        title: "Waterfront Condo in Madison Park",
        price: 2800000,
        type: "Apartment",
        area: 2100,
        rooms: 5,
        bedrooms: 2,
        features: ["Balcony", "Elevator", "Parking", "Central AC"],
        image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&q=80&w=800",
        address: "98112 Seattle, WA",
        lat: 47.6356,
        lng: -122.2801,
        description: "Luxury living on Lake Washington. Private boat slip included, along with panoramic views of the water and mountains.",
        link: "#"
    },
    {
        id: 11,
        title: "Bright Studio near Alki Beach",
        price: 420000,
        type: "Studio",
        area: 500,
        rooms: 1,
        bedrooms: 0,
        features: ["Parking"],
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800",
        address: "98116 Seattle, WA",
        lat: 47.5794,
        lng: -122.4106,
        description: "Top floor studio in West Seattle just steps from Alki beach. Includes one parking spot and storage unit.",
        link: "#"
    },
    {
        id: 12,
        title: "New Townhome in Columbia City",
        price: 780000,
        type: "House",
        area: 1450,
        rooms: 4,
        bedrooms: 2,
        features: ["Balcony", "Parking", "Central AC"],
        image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=800",
        address: "98118 Seattle, WA",
        lat: 47.5604,
        lng: -122.2871,
        description: "Eco-friendly modern townhome. Mini-splits provide efficient heating/cooling. Close to Columbia City light rail station.",
        link: "#"
    },
    {
        id: 13,
        title: "Mid-Century Modern in Magnolia",
        price: 1650000,
        type: "House",
        area: 2400,
        rooms: 7,
        bedrooms: 4,
        features: ["Terrace", "Parking", "Central AC"],
        image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800",
        address: "98199 Seattle, WA",
        lat: 47.6394,
        lng: -122.3995,
        description: "Stunning 1960s architecture with sweeping views of the Puget Sound and Olympic Mountains. Floor to ceiling glass.",
        link: "#"
    },
    {
        id: 14,
        title: "Architectural Marvel in Laurelhurst",
        price: 4150000,
        type: "House",
        area: 5200,
        rooms: 10,
        bedrooms: 5,
        features: ["Terrace", "Parking", "Central AC"],
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=800",
        address: "98105 Seattle, WA",
        lat: 47.6596,
        lng: -122.2743,
        description: "Private compound in exclusive Laurelhurst. Features an indoor pool, home theater, and expansive manicured grounds.",
        link: "#"
    },
    {
        id: 15,
        title: "Downtown Seattle High-Rise",
        price: 2150000,
        type: "Apartment",
        area: 1800,
        rooms: 4,
        bedrooms: 2,
        features: ["Elevator", "Parking", "Central AC"],
        image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=800",
        address: "98101 Seattle, WA",
        lat: 47.6101,
        lng: -122.3344,
        description: "Luxury 35th-floor living above Pacific Place. Unobstructed city skyline views, 5-star building amenities.",
        link: "#"
    },
    {
        id: 16,
        title: "Large Family Home in Wallingford",
        price: 1850000,
        type: "House",
        area: 3100,
        rooms: 8,
        bedrooms: 5,
        features: ["Terrace", "Parking"],
        image: "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&q=80&w=800",
        address: "98103 Seattle, WA",
        lat: 47.6595,
        lng: -122.3353,
        description: "Fully remodeled classic home in heart of Wallingford. Great schools, large basement play area, and huge front porch.",
        link: "#"
    },
    {
        id: 17,
        title: "Live/Work Studio in Fremont",
        price: 595000,
        type: "Studio",
        area: 850,
        rooms: 1,
        bedrooms: 0,
        features: ["Parking", "Central AC"],
        image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&q=80&w=800",
        address: "98103 Seattle, WA",
        lat: 47.6511,
        lng: -122.3498,
        description: "Unique open-concept space in the Center of the Universe. Commercial zoning allowed. Perfect for artist or small business.",
        link: "#"
    },
    {
        id: 18,
        title: "Charming Condo in Mount Baker",
        price: 680000,
        type: "Apartment",
        area: 950,
        rooms: 3,
        bedrooms: 2,
        features: ["Balcony", "Parking"],
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800",
        address: "98144 Seattle, WA",
        lat: 47.5768,
        lng: -122.2891,
        description: "Quiet lake-view unit near Mount Baker beach. Updated kitchen, hardwood floors, and a sunny east-facing deck.",
        link: "#"
    },
    {
        id: 19,
        title: "Modern Estate in Broadmoor",
        price: 5200000,
        type: "House",
        area: 6000,
        rooms: 12,
        bedrooms: 6,
        features: ["Terrace", "Parking", "Central AC"],
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
        address: "98112 Seattle, WA",
        lat: 47.6358,
        lng: -122.2922,
        description: "Incredible new construction inside the Broadmoor gated community. Features a golf simulator, wine cellar, and guest house.",
        link: "#"
    },
    {
        id: 20,
        title: "Lake Union Houseboat",
        price: 1250000,
        type: "House",
        area: 1200,
        rooms: 3,
        bedrooms: 1,
        features: ["Terrace"],
        image: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&q=80&w=800",
        address: "98109 Seattle, WA",
        lat: 47.6373,
        lng: -122.3338,
        description: "Sleepless in Seattle style floating home. Launch your paddleboard directly from the living room deck.",
        link: "#"
    }
];
